---
name: Requirements Form
title: 'Requirements Form'
labels: 'Reqs'


body:
  - type: markdown
    attributes:
      value: |
        A clear and concise name describing the System to be built
  - type: input
    id: Name
    attributes:
      label: Name of System
      description:  A clear and concise name describing the System to be built
      placeholder: ex. GitHub Issue 
    validations:
      required: true
      
