---
name: Requirements Form
about: Let's document our requirements!
title: ''
labels: ''
assignees: ''

---
**#1 System Name**
A clear and concise name describing the System to be built

**#2 Major System Capabilities**
Specify the major system capabilities in terms of availability, target deployment environment(s), device accessibility, and/or technical capability.

For example:
System must be available on the Internet
System must be available 24 hours per day
System must be able to access internal Wiley services hosting in our DC’s
System must be Firewalled

**#3 Major System Conditions**
Specify major system assumptions and/or constraints (aka conditions). The conditions may limit the options available to the designer/developer. 

For example:
System must be Highly available
System must have DR capabilities
System must interface with Azure OpenAI

**#4 System Interfaces**
Describe the dependency and relationship requirements of the system to other enterprise/external systems. Include any interface to a future system or one under development. For clarity, a graphical representation of the interfaces should be used when appropriate by providing a link.

**#5 System User Characteristics**
Identify each type of user of the system by function, location, and type of device. Specify the number of users in each group and the nature of their use of the system if applicable.

**#6 Policy Requirements**
Specify relevant applicable policies, and standards that will affect the operation and performance of the system, as well as any relevant external regulatory requirements, or constraints imposed by normal business practices.

**#7 Regulatory Requirements**
Specify relevant applicable regulations, and standards that will affect the operation and performance of the system, as well as any relevant external regulatory requirements, or constraints imposed by normal business practices.

**#8 Security requirements for users of the system**
Specify relevant applicable Security Requirements that will affect the operation and performance of the system, as well as any relevant external regulatory requirements, or constraints imposed by normal business practices.

**#9 Specify Training requirements for the system.**
Describe any formal or informal traning requirements needed to maintain and operate this System

**#10 Initial Capacity Requirements**
Identify the highest and lowest estimated number of transactions, processing frequency, and expected usage (including any seasonal peaks) for capacity planning for storage and memory requirements for the application or project.

**#11 Systems Architecture**
Specify the cloud type (AWS, Azure, GCP), compute, managed databases, and any others cloud services required for the application or project.

**#12 Cloud Requirements**
Identify any specialized cloud requirements that must be purchased in support of the implementation of the application or project.

**#13 Software Requirements**
Identify any specialized software requirements that must be purchased prior to development, or in support of the implementation, of the application or project.

**#14 Image Requirements**
Identify any Wiley base images that will be used for the development of the application or project.

**#15 System Acceptance Criteria**
Specify the general system acceptance criteria specified and agreed upon by the project sponsor and key stakeholders that will be used to accept the final end product
For example:
· Successful High availability testing
· Successful DR testing
· Connectivity testing
· Application health testing
· Cost analysis inline with estimated costs

**#16 Current System Analysis**
If a current system exists, perform analysis on the system and describe how the current system is used by the business. Specify data storage requirements, relevant data flows, system interfaces to existing systems, reporting capability, etc
