---
name: Cloud services Requirements Form
title: 'Requirements Form'
about: Let's document our requirements
labels: 'Reqs'


body:
  - type: markdown
    attributes:
      value: |
        A clear and concise name describing the System to be built
  - type: input
    id: SystemName
    attributes:
      label: Name of System
      description:  A clear and concise name describing the System to be built
      placeholder: ex. GitHub Issue 
    validations:
      required: true
      
