name: Cloud Requirements
description: Cloud Requirements form
title: "Cloud Services Requirements "
labels: [Requirements]
assignees:
  - rkoller49
body:
  - type: markdown
    attributes:
      value: |
        A clear and concise name describing the System to be built
        
  - type: textarea
    id: Name
    attributes:
      label: System Name
      description: What is the name of this System?
      render: shell
    validations:
      required: true

  - type: textarea
    id: capabilities
    attributes:
      label: Major System Capabilities
      description: Specify the major system capabilities in terms of availability, target deployment environment(s), device accessibility, and/or technical capability.
      render: shell
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Major System Conditions
      description: Specify major system assumptions and/or constraints (aka conditions). The conditions may limit the options available to the designer/developer.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: Level
    attributes:
      label: What kind of level is this tip?
      description: What level of developer do you tthink this tip is aimed at?
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true


