name: Cloud Requirements
description: Cloud Requirements form
title: "Cloud Services Requirements "
labels: [Requirements]
assignees:
  - rkoller49
body:
  - type: markdown
    attributes:
      value: |
        A clear and concise name describing the System to be built
        
  - type: textarea
    id: Name
    attributes:
      label: System Name
      description: What is the name of this System?
      render: shell
    validations:
      required: true

  - type: textarea
    id: capabilities
    attributes:
      label: System Capabilities
      description: Specify the major system capabilities in terms of availability, target deployment environment(s), device accessibility, and/or technical capability.
      render: shell
    validations:
      required: true

  - type: textarea
    id: conditions
    attributes:
      label: Major System Conditions
      description: Specify major system assumptions and/or constraints (aka conditions). The conditions may limit the options available to the designer/developer.
      render: shell
    validations:
      required: true

  - type: textarea
    id: Interfaces
    attributes:
      label: System Interfaces
      description: Describe the dependency and relationship requirements of the system to other enterprise/external systems. Include any interface to a future system or one under development. For clarity, a graphical representation of the interfaces should be used when appropriate by providing a link.
      render: shell
    validations:
      required: true

  - type: textarea
    id: Users
    attributes:
      label: System User Characteristics 
      description: Identify each type of user of the system by function, location, and type of device. Specify the number of users in each group and the nature of their use of the system if applicable.
      render: shell
    validations:
      required: true
      
  - type: dropdown
    id: Level
    attributes:
      label: What kind of level is this tip?
      description: What level of developer do you tthink this tip is aimed at?
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true


